language: c
dist: xenial
arch:
#  - amd64
  - ppc64le

before_script:
 - modprobe virtio_net
 - modprobe virtio_blk

script:
  - ./autogen
  - ./configure
  - make
  - sudo make check
  - sudo make install

after_script:
  - cat ./test/test-suite.log
  - ls /sys/devices
